version: "3.9"
services:
  controlpanel:
    container_name: "controlpanel"
    build: .
    command: "tail -f /dev/null"
    networks:
      controlpanel:
        ipv4_address: 172.16.238.10
        ipv6_address: "2001:3984:3989::10"
    ports:
    - "8080:80"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./etc/modules-load.d/:/etc/modules-load.d/
    - ./etc/sysctl.d/:/etc/sysctl.d/

networks:
  controlpanel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"